_sfhelmets append [
    "CUP_H_RUS_Altyn_black",
    "CUP_H_RUS_Altyn_facewear_black",
    "CUP_H_RUS_Altyn_Shield_Down_black",
    "CUP_H_RUS_Altyn_Shield_Up_black",
    "CUP_H_RUS_Altyn",
    "CUP_H_RUS_Altyn_facewear",
    "CUP_H_RUS_Altyn_Shield_Down",
    "CUP_H_RUS_Altyn_Shield_Up",
    "CUP_H_RUS_Altyn_khaki",
    "CUP_H_RUS_Altyn_facewear_khaki",
    "CUP_H_RUS_Altyn_Shield_Down_khaki",
    "CUP_H_RUS_Altyn_Shield_Up_khaki",
    "CUP_H_PMC_Beanie_Headphones_Khaki",
    "CUP_H_PMC_EP_Headset",
    "CUP_H_OpsCore_Covered_AAF_NoHS",
    "CUP_H_OpsCore_Covered_AAF",
    "CUP_H_RUS_K6_3_Shield_Up_khaki",
    "CUP_H_RUS_K6_3_Shield_Down_khaki",
    "CUP_H_RUS_K6_3_facewear_khaki",
    "CUP_H_RUS_K6_3_khaki",
    "CUP_H_RUS_K6_3_Shield_Up",
    "CUP_H_RUS_K6_3_Shield_Down",
    "CUP_H_RUS_K6_3_facewear",
    "CUP_H_RUS_K6_3",
    "CUP_H_RUS_K6_3_Shield_Up_black",
    "CUP_H_RUS_K6_3_Shield_Down_black",
    "CUP_H_RUS_K6_3_facewear_black",
    "CUP_H_RUS_K6_3_black",
    "CUP_H_FR_Headset"
];
_sfbackpacks append [
    "CUP_B_Kombat_Olive",
    "CUP_B_AlicePack_OD"
];
_sfvests append [];
_sfHvests append [];
//////////////////////////////////////////////////////
_elitehelmets append [
    "CUP_H_RUS_Altyn_black",
    "CUP_H_RUS_Altyn_facewear_black",
    "CUP_H_RUS_Altyn_Shield_Down_black",
    "CUP_H_RUS_Altyn_Shield_Up_black",
    "CUP_H_RUS_Altyn",
    "CUP_H_RUS_Altyn_facewear",
    "CUP_H_RUS_Altyn_Shield_Down",
    "CUP_H_RUS_Altyn_Shield_Up",
    "CUP_H_RUS_Altyn_khaki",
    "CUP_H_RUS_Altyn_facewear_khaki",
    "CUP_H_RUS_Altyn_Shield_Down_khaki",
    "CUP_H_RUS_Altyn_Shield_Up_khaki",
    "CUP_H_PMC_Beanie_Headphones_Khaki",
    "CUP_H_PMC_EP_Headset",
    "CUP_H_OpsCore_Covered_AAF_NoHS",
    "CUP_H_OpsCore_Covered_AAF",
    "CUP_H_RUS_K6_3_Shield_Up_khaki",
    "CUP_H_RUS_K6_3_Shield_Down_khaki",
    "CUP_H_RUS_K6_3_facewear_khaki",
    "CUP_H_RUS_K6_3_khaki",
    "CUP_H_RUS_K6_3_Shield_Up",
    "CUP_H_RUS_K6_3_Shield_Down",
    "CUP_H_RUS_K6_3_facewear",
    "CUP_H_RUS_K6_3",
    "CUP_H_RUS_K6_3_Shield_Up_black",
    "CUP_H_RUS_K6_3_Shield_Down_black",
    "CUP_H_RUS_K6_3_facewear_black",
    "CUP_H_RUS_K6_3_black",
    "CUP_H_FR_Headset"
];
_elitebackpacks append [
    "CUP_B_Kombat_Olive",
    "CUP_B_AlicePack_OD"
];
_elitevests append [
    "CUP_V_B_Ciras_Olive4",
    "CUP_V_B_Ciras_Olive3",
    "CUP_V_B_Ciras_Olive2",
    "CUP_V_B_Ciras_Olive",
    "CUP_V_B_Armatus_OD",
    "CUP_V_B_Armatus_BB_OD",
    "CUP_V_PMC_IOTV_Black_Patrol",
    "CUP_V_PMC_IOTV_Black_TL",
    "CUP_V_PMC_IOTV_Black_Empty",
    "CUP_V_PMC_IOTV_Black_AR"
];
_eliteHvests append [
    "CUP_V_PMC_IOTV_Black_Gren",
    "CUP_V_CZ_NPP2006_co_black",
    "CUP_V_CZ_NPP2006_ok_black",
    "CUP_V_CZ_NPP2006_vz95_black",
    "CUP_V_CZ_NPP2006_nk_black"
];
//////////////////////////////////////////////////////
_militaryhelmets append [
    "CUP_H_PMC_Beanie_Headphones_Khaki",
    "CUP_H_OpsCore_Covered_AAF_NoHS",
    "CUP_H_OpsCore_Covered_AAF",
    "CUP_H_PMC_EP_Headset"
];
_militarybackpacks append [
    "CUP_B_Kombat_Olive",
    "CUP_B_AlicePack_OD"
];
_militaryvests append [
    "CUP_V_PMC_CIRAS_OD_Veh",
    "CUP_V_PMC_CIRAS_OD_Empty",
    "CUP_V_PMC_CIRAS_OD_Grenadier",
    "CUP_V_PMC_CIRAS_OD_TL",
    "CUP_V_PMC_CIRAS_OD_Patrol",
    "CUP_V_CPC_communications_rngr",
    "CUP_V_CPC_Fast_rngr",
    "CUP_V_CPC_light_rngr",
    "CUP_V_CPC_medical_rngr",
    "CUP_V_CPC_tl_rngr",
    "CUP_V_CPC_weapons_rngr",
    "CUP_V_CPC_communicationsbelt_rngr",
    "CUP_V_CPC_Fastbelt_rngr",
    "CUP_V_CPC_lightbelt_rngr",
    "CUP_V_CPC_medicalbelt_rngr",
    "CUP_V_CPC_tlbelt_rngr",
    "CUP_V_CPC_weaponsbelt_rngr",
    "CUP_V_B_Interceptor_Base_Olive",
    "CUP_V_B_Interceptor_Grenadier_Olive",
    "CUP_V_B_Interceptor_Rifleman_Olive",
    "CUP_V_JPC_weaponsbelt_rngr",
    "CUP_V_JPC_tlbelt_rngr",
    "CUP_V_JPC_medicalbelt_rngr",
    "CUP_V_JPC_lightbelt_rngr",
    "CUP_V_JPC_Fastbelt_rngr",
    "CUP_V_JPC_communicationsbelt_rngr",
    "CUP_V_JPC_weapons_rngr",
    "CUP_V_JPC_tl_rngr",
    "CUP_V_JPC_medical_rngr",
    "CUP_V_B_JPC_OD_Light",
    "CUP_V_JPC_Fast_rngr",
    "CUP_V_JPC_communications_rngr"
];
_militaryHvests append [
    "CUP_V_B_Ciras_Olive4",
    "CUP_V_B_Ciras_Olive3",
    "CUP_V_B_Ciras_Olive2",
    "CUP_V_B_Ciras_Olive"
];
//////////////////////////////////////////////////////
_militiahelmets append [
    "CUP_H_PMC_Beanie_Headphones_Khaki",
    "CUP_H_RUS_ZSH_1_facewear",
    "CUP_H_RUS_ZSH_1",
    "CUP_H_PASGTv2_OD",
    "CUP_H_PASGTv2_NVG_OD",
    "CUP_H_USArmy_Helmet_ECH1_Green",
    "CUP_H_USArmy_Helmet_ECH2_GREEN",
    "CUP_H_USArmy_Helmet_ECH1_Black",
    "CUP_H_USArmy_Helmet_ECH2_Black",
    "CUP_H_PMC_EP_Headset"
];
_militiavests append [
    "CUP_V_B_RRV_TL",
    "CUP_V_B_RRV_Scout3_GRN",
    "CUP_V_B_RRV_Scout2",
    "CUP_V_B_RRV_Scout",
    "CUP_V_B_RRV_Officer",
    "CUP_V_B_RRV_Medic",
    "CUP_V_B_RRV_MG_GRN",
    "CUP_V_I_RACS_Carrier_Rig_wdl_3",
    "CUP_V_I_RACS_Carrier_Rig_wdl_2"
];
_militiabackpacks append [
    "CUP_B_Kombat_Olive",
    "CUP_B_AlicePack_OD"
];
_militiaHvests append [
    "CUP_V_B_PASGT_no_bags_OD",
    "CUP_V_B_PASGT_OD"
];
